from pathlib import Path
from pdf_fetcher.indexer import QdrantIndexer
from pdf_fetcher.rag import PDFRAG

# 1. Initialize the Qdrant indexer client and database configuration
indexer = QdrantIndexer()

# 2. Recreate or load the collection; logic inside skips if it already exists
indexer.create_collection()

# 3. Define the path to the directory containing all source PDF documents
pdf_directory = Path("data/pdfs")

# 4. Scan the directory and index all valid PDF files into the Qdrant database
indexer.index_specific_pdfs(pdf_directory)

# 5. Safely close the indexer client storage connection after processing files
indexer.client.close()

# 6. Initialize the core Retrieval-Augmented Generation (RAG) pipeline engine
rag = PDFRAG()

print("RAG system is ready.")
print("Type 'exit', 'quit', or 'q' to stop the program.\n")

# 7. Start an interactive conversational loop to capture continuous user queries
while True:
    # Accept user query directly from the terminal interface
    question = input("Type question here: ")

    # Check for exit signals to break the loop and terminate safely
    if question.lower().strip() in {"exit", "quit", "q"}:
        print("Shutting down the RAG session. Goodbye!")
        break

    # Guard clause against empty or whitespace-only inputs
    if not question.strip():
        continue

    # 8. Pass the user question into the RAG pipeline to search context and invoke LLM
    result = rag.ask(question)

    # 9. Output the clean, natural language response generated by the Qwen3.5 LLM
    print("\nAnswer:")
    print(result["answer"])

    # 10. Print structured metadata references showing exact file, page numbers, and similarity metrics
    print("\nSources:")
    for source in result["sources"]:
        print(
            f"- {source['file']} | "
            f"page {source['page']} | "
            f"score={source['score']:.3f}"
        )

    # 11. Print the localized absolute path to the generated context page screenshot
    print("\nSCREENSHOT:")
    print(result["screenshot"])

    # Visual separator block to distinguish between consecutive questions
    print("\n" + "=" * 80 + "\n")
